/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx}",
    "../trpc-ui/src/**/*.{js,ts,jsx,tsx}",
  ],
  plugins: [require("@tailwindcss/typography")],
  theme: {
    extend: {
      colors: {
        actuallyWhite: "#ffffff",
        error: "#ef4444",
        light: "#f8fafc",
        mainBackground: "#f9fafb",
        mutationBg: "#eff6ff",
        mutationBgDark: "#dbeafe",
        mutationSolid: "#3b82f6",
        mutationText: "#2563eb",
        neutralBg: "#f1f5f922",
        neutralBgDark: "#e2e8f0",
        neutralBgVeryDark: "#3f3f46",
        neutralSolid: "#52525b",
        neutralSolidTransparent: "#64748b",
        neutralText: "#0f172a",
        overlayBackground: "#999a9b88",
        panelBorder: "#d4d4d8",
        queryBg: "#f0fdf4",
        queryBgDark: "#dcfce7",
        querySolid: "#22c55e",
        queryText: "#16a34a",
        routerBg: "#faf5ffaa",
        routerBgDark: "#f3e8ff",
        routerSolid: "#8b5cf6",
        routerText: "#9333ea",
        selectedListItem: "#063352",
        separatorLine: "#d4d4d888",
        subscriptionBg: "#FEF0EC",
        subscriptionBgDark: "#FCD1C5",
        subscriptionSolid: "#F34213",
        subscriptionText: "#E93C0C",
        white: "#fcfcfc", // not actually white btw
        whiteLessTransparent: "#ffffffcc",
        whiteTransparent: "#ffffff77",
      },
    },
  },
};
